os: linux
language: python
python: "3.9"
dist: xenial

stages:
  - lint
  - test
  - publish

jobs:
  include:
    - stage: lint
      install:
        - pip install pycodestyle restructuredtext_lint pygments
      script:
        - pycodestyle --ignore=E501,W504,E275  --show-source $(find centrifuge_cli -name '*.py')
        - rst-lint README.rst
    - stage: test
      install:
        - pip install pytest toml
      script:
        - pytest
    - stage: publish
      script: skip
      before_deploy:
        - pip install --upgrade pip
        - pip install poetry
        - poetry config http-basic.pypi $PYPI_USER $PYPI_PASS
        - poetry build
      deploy:
        skip_cleanup: true
        provider: script
        script: poetry publish
        on:
          tags: true
      if: tag IS present
